stages:
  - build
  - deploy

build:
  stage: build
  image: node:24-alpine
  script:
    - npm ci
    - npm run build

deploiement:
  stage: deploy
  image: alpine:3.20
  script:
    - echo "Déploiement"
