stages:
  - quality
  - build
  - deploy

lint:
  stage: quality
  image: node:24-alpine
  script:
    - npm ci
    - npm run lint

build:
  stage: build
  image: node:24-alpine
  script:
    - npm ci
    - npm run build
